docs: move from multiwerf to trdl
werf/werf pull request #3698
Opened 2021-09-06 18:45 UTC by distorhead

2021-09-07 21:40 UTC, alexey-igrychev requested changes

2021-09-07 21:40 UTC, alexey-igrychev commented on docs/site/_includes/en/installation/trdl_windows.md
> +Invoke-WebRequest -Uri https://tuf.trdl.dev/targets/releases/0.1.3/windows-{{ include.arch }}/bin/trdl.exe -OutFile $TRDL_BIN_PATH\werf.exe
```suggestion
Invoke-WebRequest -Uri https://tuf.trdl.dev/targets/releases/0.1.3/windows-{{ include.arch }}/bin/trdl.exe -OutFile $TRDL_BIN_PATH\trdl.exe
```

2021-09-07 21:40 UTC, alexey-igrychev commented on docs/site/_includes/ru/installation/trdl_windows.md
> +Invoke-WebRequest -Uri https://tuf.trdl.dev/targets/releases/0.1.3/windows-{{ include.arch }}/bin/trdl.exe -OutFile $TRDL_BIN_PATH\werf.exe
```suggestion
Invoke-WebRequest -Uri https://tuf.trdl.dev/targets/releases/0.1.3/windows-{{ include.arch }}/bin/trdl.exe -OutFile $TRDL_BIN_PATH\trdl.exe
```

2021-09-08 11:16 UTC, ilya-lesikov approved these changes

2021-09-08 14:07 UTC, merged